Repository FLEX-RATE/flexrate-front, pull requests merged in 2025-06, with the labels that each got.

#71 feat: 마이페이지 이메일 변경 API 연동
  src/app/mypage/edit-email/page.tsx
  src/app/mypage/edit/page.tsx
  src/components/MypageEditFunnel/CodeVerificationStep/CodeVerificationStep.tsx
  src/components/MypageEditFunnel/CompleteStep/CompleteStep.tsx
  src/components/MypageEditFunnel/EmailStep/EmailStep.style.tsx
  src/components/MypageEditFunnel/EmailStep/EmailStep.tsx
  src/components/MypageEditFunnel/MypageEditFunnel.tsx
  src/hooks/useEmailVerification.ts
  src/hooks/useVerifyEmailCode.ts
Labels: feat

#78 fix: 만료된 리프레쉬 토큰 재발급 무한루프 문제 개선
  src/apis/auth.ts
  src/apis/client.ts
  src/hooks/useInitUser.ts
Labels: bug, hotfix

#84 fix: fix: PIN 삭제 버튼 동작하지 않던 오류 수정
  src/components/login/LoginSelector/LoginSelector.tsx
  src/components/signup/SignupPinForm/SignupPinForm.tsx
  src/components/verify/PinVerify.tsx
Labels: fix

#85 feat: NotFound 페이지 생성
  public/icons/webeeX.svg
  src/app/not-found.tsx
Labels: feat

#94 fix: QA 2차 개선사항 반영
  src/app/loan-result/page.tsx
  src/app/mypage/edit/page.tsx
  src/app/mypage/page.style.ts
  src/app/mypage/page.tsx
  src/app/notifications/page.style.ts
  src/app/page.tsx
  src/components/AreaChart/AreaChart.tsx
  src/components/Button/Button.style.ts
  src/components/Header/Header.tsx
  src/components/MainHasLoan/MainHasLoan.style.ts
  src/components/MypageEditFunnel/CompleteStep/CompleteStep.style.ts
  src/components/MypageEditFunnel/CompleteStep/CompleteStep.tsx
  src/components/MypageEditFunnel/EmailStep/EmailStep.style.tsx
  src/components/MypageEditFunnel/MypageEditFunnel.style.ts
  src/components/admin/Header/Header.tsx
  src/components/creditEvaluationStep/AgreementEvaluation/AgreementEvaluation.style.ts
  src/components/loanApplicationFunnel/CreditStep/CreditStep.style.ts
  src/components/loanApplicationFunnel/LoanApplicationFunnel.style.ts
  src/components/loanApplicationFunnel/ReviewResultAndLoanApplication/ReviewResultAndLoanApplication.style.ts
  src/components/loanApplicationFunnel/ReviewResultAndLoanApplication/ReviewResultAndLoanApplication.tsx
  src/components/main/IntroduceHome/IntroduceHome.style.ts
  src/components/signup/AgreeForConsumptionType/AgreeForConsumptionType.tsx
  src/hooks/useLoanApplication.ts
  src/hooks/useLoginUser.ts
  src/schemas/application.schema.ts
  src/schemas/auth.schema.ts
  src/styles/MobileGlobalStyle/MobileGlobalStyle.style.ts
Labels: bug, fix

#95 feat: 어드민 페이지 접근 권한 설정 및 로그인 라우팅 지정
  src/components/admin/AdminLayout/AdminLayout.tsx
  src/components/admin/Header/Header.style.ts
  src/components/admin/Header/Header.tsx
  src/hooks/useAuthGuard.ts
  src/hooks/useLoginUser.ts
  src/stores/userStore.ts
  src/types/auth.type.ts
Labels: feat

#98 fix: 소비 통계 원 해상도별 위치 조정 및 로그인 회원가입 버튼 관련 추가 작업
  src/app/auth/signup/page.tsx
  src/app/consumption-report/page.tsx
  src/components/Header/Header.tsx
  src/components/login/LoginSelector/LoginSelector.style.ts
  src/components/login/LoginSelector/LoginSelector.tsx
Labels: fix

#101 fix: AdminBody 최소 너비 1050px 설정
  src/components/admin/AdminLayout/AdminLayout.style.ts
Labels: refactor
