Repository FLEX-RATE/flexrate-front, pull requests merged in 2025-05, with the labels that each got.

#4 feat: theme color, typo 작업 및 admin 레이아웃 작업
  next.config.mjs
  pnpm-lock.yaml
  public/fonts/PretendardVariable.woff2
  src/app/admin/layout.tsx
  src/app/admin/page.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/app/middleware.ts
  src/assets/fonts/GeistMonoVF.woff
  src/assets/fonts/GeistVF.woff
  src/assets/img/logo(green).png
  src/components/admin/AdminLayout/AdminLayout.style.ts
  src/components/admin/AdminLayout/AdminLayout.tsx
  src/components/admin/Header/Header.style.ts
  src/components/admin/Header/Header.tsx
  src/components/admin/Sidebar/Sidebar.style.ts
  src/components/admin/Sidebar/Sidebar.tsx
  src/styles/colors.ts
  src/styles/globalStyle.ts
  src/styles/typos.ts
  tsconfig.json
Labels: feat

#9 feat: GlobalStyle(데스크탑, 모바일 뷰) 분기 작업
  src/app/layout.tsx
  src/components/GlobalStyleProvider/GlobalStyleProvider.tsx
  src/styles/DesktopGlobalStyle/DesktopGlobalStyle.style.ts
  src/styles/DesktopGlobalStyle/DesktopGlobalStyle.tsx
  src/styles/MobileGlobalStyle/MobileGlobalStyle.style.ts
  src/styles/MobileGlobalStyle/MobileGlobalStyle.tsx
  src/styles/colors.ts
Labels: feat

#6 feat: 관리자 페이지 고객 관리 메뉴 UI 구현
  .eslintrc.json
  package.json
  pnpm-lock.yaml
  src/app/admin/customer-management/page.style.ts
  src/app/admin/customer-management/page.tsx
  src/app/admin/layout.tsx
  src/components/admin/Sidebar/Sidebar.style.ts
  src/components/admin/conditionbar/Conditionbar.style.ts
  src/components/admin/conditionbar/Conditionbar.tsx
  src/components/admin/dataTable/DataTable.style.ts
  src/components/admin/dataTable/DataTable.tsx
  src/hooks/useCustomersQuery.ts
  src/stores/filterStore.ts
  src/types/filter.type.ts
  tsconfig.json
Labels: feat

#12 feat: Button 공통 컴포넌트 작업
  src/components/Button/Button.style.ts
  src/components/Button/Button.tsx
  src/components/Button/Button.type.ts
  src/styles/colors.ts
Labels: feat

#15 feat: TextField 공통 컴포넌트 작업
  next.config.mjs
  package.json
  pnpm-lock.yaml
  src/assets/icons/delete_24.svg
  src/assets/icons/error_18.svg
  src/assets/icons/error_24.svg
  src/components/TextField/TextField.style.ts
  src/components/TextField/TextField.tsx
  src/components/TextField/TextField.type.ts
  src/components/TextField/TextFieldContext.ts
  src/lib/getInputType.ts
  src/styles/colors.ts
Labels: feat

#18 feat: 관리자 페이지 - 고객 관리 메뉴 스켈레톤 UI 추가 및 API 연동
  src/app/admin/customer-management/page.tsx
  src/app/admin/not-found/page.tsx
  src/assets/icons/userDetailButton.svg
  src/components/admin/Conditionbar/Conditionbar.style.ts
  src/components/admin/Conditionbar/Conditionbar.tsx
  src/components/admin/DataTable/DataTable.style.ts
  src/components/admin/DataTable/DataTable.tsx
  src/components/admin/conditionbar/Conditionbar.style.ts
  src/components/admin/conditionbar/Conditionbar.tsx
  src/components/admin/dataTable/DataTable.tsx
  src/components/admin/skeleton/TableSkeleton/TableSkeleton.style.ts
  src/components/admin/skeleton/TableSkeleton/TableSkeleton.tsx
  src/hooks/useCustomersQuery.ts
  src/stores/filterStore.ts
  src/types/filter.type.ts
  src/types/svg.d.ts
Labels: feat

#24 feat: 관리자 페이지 사이드바 구현
  src/apis/auth.ts
  src/assets/icons/profile_24.svg
  src/components/admin/Header/Header.style.ts
  src/components/admin/Header/Header.tsx
  src/components/admin/Sidebar/Sidebar.style.ts
  src/components/admin/Sidebar/Sidebar.tsx
  src/hooks/useInitUser.ts
  src/stores/userStore.ts
Labels: feat

#27 feat: 관리자 페이지 - 고객 관리 메뉴 필드 편집 UI 및 API 연동
  src/apis/adminMembers.ts
  src/app/admin/customer-management/page.tsx
  src/components/admin/DataTable/DataTable.tsx
  src/components/admin/EditableCell/EditableCell.tsx
  src/hooks/useMembersQuery.ts
  src/hooks/usePatchMember.ts
  src/utils/memberParams.ts
Labels: feat

#28 feat: 대출 심사 신청 및 결과 페이지 & 대출 신청 및 결과 페이지 UI 작업
  .eslintrc.json
  .prettierignore
  package.json
  pnpm-lock.yaml
  public/icons/backArrow_36.svg
  public/icons/downArrow_24.svg
  public/icons/upArrow_24.svg
  src/app/loan-application/page.tsx
  src/app/loan-result/page.tsx
  src/components/Accordion/Accordion.style.ts
  src/components/Accordion/Accordion.tsx
  src/components/Button/Button.style.ts
  src/components/Button/Button.tsx
  src/components/Button/Button.type.ts
  src/components/Header/Header.style.ts
  src/components/Header/Header.tsx
  src/components/ProgressBar/ProgressBar.style.ts
  src/components/ProgressBar/ProgressBar.tsx
  src/components/TextField/TextField.tsx
  src/components/TextField/TextField.type.ts
  src/components/loanApplicationFunnel/CreditStep/CreditStep.style.ts
  src/components/loanApplicationFunnel/CreditStep/CreditStep.tsx
  src/components/loanApplicationFunnel/JobStep/JobStep.style.ts
  src/components/loanApplicationFunnel/JobStep/JobStep.tsx
  src/components/loanApplicationFunnel/LoanApplicationFunnel.style.ts
  src/components/loanApplicationFunnel/LoanApplicationFunnel.tsx
  src/components/loanApplicationFunnel/PurposeStep/PurposeStep.style.ts
  src/components/loanApplicationFunnel/PurposeStep/PurposeStep.tsx
  src/components/loanApplicationFunnel/ReviewResultAndLoanApplication/ReviewResultAndLoanApplication.style.ts
  src/components/loanApplicationFunnel/ReviewResultAndLoanApplication/ReviewResultAndLoanApplication.tsx
  src/components/main/IntroduceHome/IntroduceHome.style.ts
  src/components/main/IntroduceHome/IntroduceHome.tsx
  src/constants/loan.constant.ts
  src/lib/getInputType.ts
  src/styles/MobileGlobalStyle/MobileGlobalStyle.style.ts
  src/styles/typos.ts
Labels: feat

#25 feat: 관리자 페이지 - 고객 상세 조회 UI
  src/apis/customer.ts
  src/apis/transactions.ts
  src/app/admin/customer-management/[userId]/page.style.ts
  src/app/admin/customer-management/[userId]/page.tsx
  src/components/admin/ErrorBlock/ErrorBlock.style.ts
  src/components/admin/ErrorBlock/ErrorBlock.tsx
  src/components/admin/InfoBlock/InfoBlock.style.ts
  src/components/admin/InfoBlock/InfoBlock.tsx
  src/constants/customer.constant.ts
Labels: feat

#32 feat: 회원가입 및 로그인 화면 UI 작업
  package.json
  pnpm-lock.yaml
  public/icons/checkbox_large_checked.svg
  public/icons/checkbox_large_unchecked.svg
  public/icons/checkbox_small_checked.svg
  public/icons/checkbox_small_unchecked.svg
  public/imgs/faceid.svg
  public/imgs/lock.svg
  public/imgs/pattern.svg
  src/apis/auth.ts
  src/app/auth/login/page.tsx
  src/app/auth/signup/page.tsx
  src/components/BottomSheet/BottomSheet.style.ts
  src/components/BottomSheet/BottomSheet.tsx
  src/components/CheckBox/CheckBox.style.ts
  src/components/CheckBox/CheckBox.tsx
  src/components/CheckBox/CheckBox.type.ts
  src/components/Header/Header.tsx
  src/components/TextField/TextField.tsx
  src/components/TextField/TextField.type.ts
  src/components/loanApplicationFunnel/CreditStep/CreditStep.tsx
  src/components/login/LoginForm/LoginForm.style.ts
  src/components/login/LoginForm/LoginForm.tsx
  src/components/login/LoginSelector/LoginSelector.style.ts
  src/components/login/LoginSelector/LoginSelector.tsx
  src/components/signup/AgreeForConsumptionType/AgreeForConsumptionType.tsx
  src/components/signup/ConsumptionGoal/ConsumptionGoal.style.ts
  src/components/signup/ConsumptionGoal/ConsumptionGoal.tsx
  src/components/signup/ConsumptionResult/ConsumptionResult.style.ts
  src/components/signup/ConsumptionResult/ConsumptionResult.tsx
  src/components/signup/EmailForm/EmailForm.style.ts
  src/components/signup/EmailForm/EmailForm.tsx
  src/components/signup/InfoForm/InfoForm.tsx
  src/components/signup/PasswordForm/PasswordForm.style.ts
  src/components/signup/PasswordForm/PasswordForm.tsx
  src/constants/auth.constant.ts
  src/schemas/auth.schema.ts
  src/types/funnel.type.ts
Labels: feat

#37 feat: 소비 습관 리포트 UI 작업
  src/app/consumption-report/page.tsx
  src/components/Header/Header.style.ts
Labels: feat

#38 feat: 신용 점수 산출 UI 작업
  src/app/auth/login/page.tsx
  src/app/auth/signup/page.tsx
  src/app/credit-evaluation/page.tsx
  src/components/CircularCart/CircularCart.tsx
  src/components/CircularCart/CircularChart.style.ts
  src/components/creditEvaluationStep/AgreementCredit.style.ts
  src/components/creditEvaluationStep/AgreementCredit/AgreementCredit.tsx
  src/components/creditEvaluationStep/AgreementEvaluation/AgreementEvaluation.style.ts
  src/components/creditEvaluationStep/AgreementEvaluation/AgreementEvaluation.tsx
  src/components/loanApplicationFunnel/LoanApplicationFunnel.tsx
  src/components/login/LoginSelector/LoginSelector.tsx
  src/components/signup/AgreeForConsumptionType/AgreeForConsumptionType.tsx
  src/components/signup/ConsumptionGoal/ConsumptionGoal.tsx
  src/components/signup/ConsumptionResult/ConsumptionResult.tsx
  src/schemas/credit.schema.ts
Labels: feat

#39 feat: 관리자 페이지 - 대출 신청 현황 UI 및 수정 기능
  src/apis/loanApplication.ts
  src/app/admin/loan-application/page.style.ts
  src/app/admin/loan-application/page.tsx
  src/hooks/useLoanApplicationsQuery.ts
  src/hooks/usePatchLoanStatus.ts
  src/stores/loanFilterStore.ts
  src/types/loan.filter.type.ts
  src/utils/loanApplicationParams.ts
Labels: feat

#41 fix: loanApplication 파일명 AdminLoans로 변경
  src/apis/AdminLoans.ts
  src/hooks/useLoanApplicationsQuery.ts
  src/hooks/usePatchLoanStatus.ts
Labels: fix

#45 feat: 대출 보유자 메인 페이지 UI 작업
  public/icons/alert_24.svg
  public/icons/alert_36.svg
  public/icons/badgeIc.svg
  public/icons/greenUpArrow.svg
  public/icons/left_slide_arrow.svg
  public/icons/right_slide_arrow.svg
  public/icons/webee_36.svg
  src/app/loan-result/page.tsx
  src/app/mypage/page.style.ts
  src/app/page.tsx
  src/components/AreaChart/AreaChart.style.ts
  src/components/AreaChart/AreaChart.tsx
  src/components/Banner/Banner.style.ts
  src/components/Banner/Banner.tsx
  src/components/Banner/Banner.type.ts
  src/components/Header/Header.style.ts
  src/components/Header/Header.tsx
  src/components/MainHasLoan/FirstPage/FirstPage.style.ts
  src/components/MainHasLoan/FirstPage/FirstPage.tsx
  src/components/MainHasLoan/MainHasLoan.style.ts
  src/components/MainHasLoan/MainHasLoan.tsx
  src/components/MainHasLoan/SecondPage/SecondPage.style.ts
  src/components/MainHasLoan/SecondPage/SecondPage.tsx
  src/components/ProgressBar/ProgressBar.style.ts
  src/components/ProgressBar/ProgressBar.tsx
  src/components/creditEvaluationStep/AgreementEvaluation/AgreementEvaluation.style.ts
  src/components/loanApplicationFunnel/CreditStep/CreditStep.style.ts
  src/components/loanApplicationFunnel/JobStep/JobStep.style.ts
  src/components/loanApplicationFunnel/LoanApplicationFunnel.style.ts
  src/components/loanApplicationFunnel/PurposeStep/PurposeStep.style.ts
  src/components/loanApplicationFunnel/ReviewResultAndLoanApplication/ReviewResultAndLoanApplication.style.ts
  src/components/login/LoginForm/LoginForm.style.ts
  src/components/main/IntroduceHome/IntroduceHome.style.ts
  src/components/main/IntroduceHome/IntroduceHome.tsx
  src/components/main/LoanDashboard/LoanDashboard.style.ts
  src/components/main/LoanDashboard/LoanDashboard.tsx
  src/components/main/MainHeader/MainHeader.style.ts
  src/components/main/MainHeader/MainHeader.tsx
  src/components/main/TabBar/TabBar.style.ts
  src/components/signup/EmailForm/EmailForm.style.ts
  src/components/signup/EmailForm/EmailForm.tsx
  src/hooks/useSlideTouch.ts
  src/schemas/auth.schema.ts
  src/styles/DesktopGlobalStyle/DesktopGlobalStyle.style.ts
  src/styles/MobileGlobalStyle/MobileGlobalStyle.style.ts
  src/styles/colors.ts
  src/styles/typos.ts
Labels: feat

#43 feat: 대출 메인 페이지 - 상품 페이지 API 연동
  src/apis/loanProducts.ts
  src/components/creditEvaluationStep/AgreementCredit.style.ts
  src/components/main/IntroduceHome/IntroduceHome.tsx
  src/hooks/useSelectLoanProduct.ts
Labels: feat

#55 feat: 신용 평가 점수 API 연동 및 회원 상태별 메인페이지 분기 처리 작업
  package.json
  pnpm-lock.yaml
  src/apis/admin.ts
  src/apis/adminMembers.ts
  src/apis/credit.ts
  src/apis/customer.ts
  src/app/admin/customer-management/[userId]/page.tsx
  src/app/auth/signup/page.tsx
  src/app/consumption-report/page.tsx
  src/app/layout.tsx
  src/app/loan-result/page.tsx
  src/app/mypage/page.tsx
  src/app/page.tsx
  src/components/BottomSheet/BottomSheet.style.ts
  src/components/BottomSheet/BottomSheet.tsx
  src/components/Button/Button.type.ts
  src/components/CircularChart/CircularChart.style.ts
  src/components/CircularChart/CircularChart.tsx
  src/components/Header/Header.tsx
  src/components/Modal/Modal.style.ts
  src/components/Modal/Modal.tsx
  src/components/creditEvaluationStep/AgreementEvaluation/AgreementEvaluation.tsx
  src/components/login/LoginForm/LoginForm.tsx
  src/components/main/IntroduceHome/IntroduceHome.tsx
  src/components/main/LoanDashboard/LoanDashboard.tsx
  src/components/signup/ConsumptionGoalStep/ConsumptionGoalStep.tsx
  src/components/signup/ConsumptionResult/ConsumptionResult.tsx
  src/components/signup/InfoForm/InfoForm.tsx
  src/hooks/useConsumptionType.ts
  src/hooks/useCreditScore.ts
  src/hooks/useInitUser.ts
  src/hooks/useLoanApplicationsQuery.ts
  src/hooks/useLoanStatus.ts
  src/hooks/useLoginUser.ts
  src/hooks/useMembersQuery.ts
  src/hooks/usePatchLoanStatus.ts
  src/hooks/usePatchMember.ts
  src/hooks/usePostSignup.ts
  src/hooks/useSelectLoanProduct.ts
  src/stores/userStore.ts
  src/types/auth.type.ts
  src/types/credit.type.ts
  src/types/user.type.ts
Labels: feat, refactor

#61 chore: build 중 발생하는 핵심 오류 개선
  next.config.mjs
  src/app/admin/not-found/page.tsx
  src/app/loan-result/page.tsx
  src/app/mypage/edit/page.tsx
  src/components/login/PinLogin/PinLogin.tsx
  src/hooks/useLoanApplicationsQuery.ts
Labels: chore

#63 feat: 메인페이지 API 연동
  src/apis/interest.ts
  src/app/page.tsx
  src/app/providers.tsx
  src/components/AreaChart/AreaChart.style.ts
  src/components/AreaChart/AreaChart.tsx
  src/components/Header/Header.tsx
  src/components/MainHasLoan/FirstPage/FirstPage.style.ts
  src/components/MainHasLoan/FirstPage/FirstPage.tsx
  src/components/MainHasLoan/MainHasLoan.tsx
  src/components/MainHasLoan/SecondPage/SecondPage.style.ts
  src/components/MainHasLoan/SecondPage/SecondPage.tsx
  src/components/main/IntroduceHome/IntroduceHome.style.ts
  src/components/main/LoanDashboard/LoanDashboard.tsx
  src/hooks/useInterestStats.ts
  src/hooks/useLoanApplication.ts
  src/hooks/useMainFirstPage.ts
  src/hooks/useMainSecondPage.ts
  src/styles/MobileGlobalStyle/MobileGlobalStyle.style.ts
  src/types/chart.type.ts
  src/types/interest.type.ts
  src/utils/dateFormat.ts
  src/utils/formatKoreanMoneyUnit.ts
  src/utils/formatNumberComma.ts
  src/utils/formatPeriodLabel.ts
Labels: feat

#65 feat: axios interceptor로 토큰 자동 재발급 작업
  src/apis/auth.ts
  src/apis/client.ts
  src/hooks/useLoginUser.ts
Labels: feat

#56 feat: 알림 페이지 UI
  package.json
  pnpm-lock.yaml
  src/apis/notification.ts
  src/app/notifications/page.style.ts
  src/app/notifications/page.tsx
  src/components/Header/Header.tsx
  src/components/Modal/Modal.tsx
  src/components/NotificationBadge/NotificationBadge.style.ts
  src/components/NotificationBadge/NotificationBadge.tsx
  src/components/NotificationItem/NotificationItem.style.ts
  src/components/NotificationItem/NotificationItem.tsx
  src/constants/notification.constant.ts
  src/hooks/useNotifications.ts
  src/hooks/useUnreadNotificationCount.ts
  src/styles/colors.ts
  src/types/event-source-polyfill.d.ts
  src/types/notification.type.ts
  src/utils/notificationDate.ts
Labels: feat
